sudo: required

language: perl

perl:
  - "5.26"

dist:
  - bionic

env:
  global:
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
install:
  - ./.travis/install.sh

addons:
  apt:
    update: true
